# Generated by Django 3.1.7 on 2021-04-19 03:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0003_auto_20210418_2015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liftingschedule',
            unique_together={('date', 'ath_user')},
        ),
        migrations.AlterUniqueTogether(
            name='throwingschedule',
            unique_together={('date', 'ath_user')},
        ),
    ]
