# Generated by Django 3.1.7 on 2021-04-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20210418_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throwing',
            name='throw_data',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throws',
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_10',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_9',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_1', to='training.throwingdescription'),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_10', to='training.throwingdescription'),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_2', to='training.throwingdescription'),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_3', to='training.throwingdescription'),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_4', to='training.throwingdescription'),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_5', to='training.throwingdescription'),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_6', to='training.throwingdescription'),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_7', to='training.throwingdescription'),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_8', to='training.throwingdescription'),
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throw_9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='throw_9', to='training.throwingdescription'),
        ),
    ]
