# Generated by Django 3.1.7 on 2021-04-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20210425_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throwing',
            name='throw_1',
        ),
        migrations.RemoveField(
            model_name='throwing',
            name='throw_10',
        ),
        migrations.RemoveField(
            model_name='throwing',
            name='throw_2',
        ),
        migrations.RemoveField(
            model_name='throwing',
            name='throw_3',
        ),
        migrations.RemoveField(
            model_name='throwing',
            name='throw_4',
        ),
        migrations.RemoveField(
            model_name='throwing',
            name='throw_5',
        ),
        migrations.RemoveField(
            model_name='throwing',
            name='throw_6',
        ),
        migrations.RemoveField(
            model_name='throwing',
            name='throw_7',
        ),
        migrations.RemoveField(
            model_name='throwing',
            name='throw_8',
        ),
        migrations.RemoveField(
            model_name='throwing',
            name='throw_9',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_1',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_10',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_2',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_3',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_4',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_5',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_6',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_7',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_8',
        ),
        migrations.RemoveField(
            model_name='throwplans',
            name='throw_9',
        ),
        migrations.AddField(
            model_name='throwing',
            name='throw_data',
            field=models.JSONField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='throwplans',
            name='throws',
            field=models.ManyToManyField(to='training.ThrowingDescription'),
        ),
    ]
