# Generated by Django 3.1.7 on 2021-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210426_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liftingdescription',
            name='lift_name',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='throwingdescription',
            name='throw_name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
