# Generated by Django 3.1.7 on 2021-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20210502_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifting',
            name='lift_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='throwing',
            name='throw_date',
            field=models.DateField(blank=True),
        ),
    ]
