# Generated by Django 3.1.7 on 2021-04-19 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftingDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_name', models.CharField(max_length=225)),
                ('lift_desc', models.CharField(max_length=225)),
                ('lift_type', models.CharField(choices=[('S', 'Stretch'), ('T', 'Tracked')], max_length=225)),
                ('lift_sets', models.IntegerField(null=True)),
                ('lift_reps', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=45)),
                ('loc_address', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ('loc_name', 'loc_address'),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ThrowingDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_name', models.CharField(max_length=225)),
                ('throw_desc', models.CharField(max_length=225)),
                ('throw_type', models.CharField(choices=[('R', 'Recovery'), ('T', 'Tracked')], max_length=225)),
                ('throw_sets', models.IntegerField(null=True)),
                ('throw_reps', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThrowPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('throws', models.ManyToManyField(to='training.ThrowingDescription')),
            ],
            options={
                'verbose_name_plural': 'Throw Plans',
            },
        ),
        migrations.CreateModel(
            name='ThrowingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('ath_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='training.throwplans')),
            ],
        ),
        migrations.CreateModel(
            name='LiftPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('lifts', models.ManyToManyField(to='training.LiftingDescription')),
            ],
            options={
                'verbose_name_plural': 'Lift Plans',
            },
        ),
        migrations.CreateModel(
            name='LiftingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('ath_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='training.liftplans')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coach_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.location')),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ath_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ath_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.location')),
                ('ath_position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='training.position')),
            ],
        ),
        migrations.CreateModel(
            name='Throwing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_date', models.DateField(auto_now_add=True)),
                ('throw_data', models.JSONField()),
                ('ath_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Throwing',
                'unique_together': {('ath_id', 'throw_date')},
            },
        ),
        migrations.CreateModel(
            name='Lifting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_date', models.DateField(auto_now_add=True)),
                ('lift_data', models.JSONField()),
                ('ath_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lifting',
                'unique_together': {('ath_id', 'lift_date')},
            },
        ),
    ]
