# Generated by Django 3.1.7 on 2021-04-19 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='ath_id',
            new_name='ath_user',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='coach_id',
            new_name='coach_user',
        ),
    ]
